//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dvbseserviceview.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dvbseserviceview.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon audioser {
            get {
                object obj = ResourceManager.GetObject("audioser", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon dataserv {
            get {
                object obj = ResourceManager.GetObject("dataserv", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        internal static string FilterAttributeTypeAudio {
            get {
                return ResourceManager.GetString("FilterAttributeTypeAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string FilterAttributeTypeBouquetList {
            get {
                return ResourceManager.GetString("FilterAttributeTypeBouquetList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CASystemID.
        /// </summary>
        internal static string FilterAttributeTypeCASystemID {
            get {
                return ResourceManager.GetString("FilterAttributeTypeCASystemID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        internal static string FilterAttributeTypeFeatures {
            get {
                return ResourceManager.GetString("FilterAttributeTypeFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreeCAMode.
        /// </summary>
        internal static string FilterAttributeTypeFreeCAMode {
            get {
                return ResourceManager.GetString("FilterAttributeTypeFreeCAMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lcn.
        /// </summary>
        internal static string FilterAttributeTypeLcn {
            get {
                return ResourceManager.GetString("FilterAttributeTypeLcn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string FilterAttributeTypeName {
            get {
                return ResourceManager.GetString("FilterAttributeTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NetworkName.
        /// </summary>
        internal static string FilterAttributeTypeNetworkName {
            get {
                return ResourceManager.GetString("FilterAttributeTypeNetworkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nid.
        /// </summary>
        internal static string FilterAttributeTypeNid {
            get {
                return ResourceManager.GetString("FilterAttributeTypeNid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string FilterAttributeTypeNone {
            get {
                return ResourceManager.GetString("FilterAttributeTypeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onid.
        /// </summary>
        internal static string FilterAttributeTypeOnid {
            get {
                return ResourceManager.GetString("FilterAttributeTypeOnid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pcr.
        /// </summary>
        internal static string FilterAttributeTypePcr {
            get {
                return ResourceManager.GetString("FilterAttributeTypePcr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pmt.
        /// </summary>
        internal static string FilterAttributeTypePmt {
            get {
                return ResourceManager.GetString("FilterAttributeTypePmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string FilterAttributeTypePosition {
            get {
                return ResourceManager.GetString("FilterAttributeTypePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        internal static string FilterAttributeTypeProvider {
            get {
                return ResourceManager.GetString("FilterAttributeTypeProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sid.
        /// </summary>
        internal static string FilterAttributeTypeSid {
            get {
                return ResourceManager.GetString("FilterAttributeTypeSid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tsid.
        /// </summary>
        internal static string FilterAttributeTypeTsid {
            get {
                return ResourceManager.GetString("FilterAttributeTypeTsid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string FilterAttributeTypeType {
            get {
                return ResourceManager.GetString("FilterAttributeTypeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        internal static string FilterAttributeTypeVideo {
            get {
                return ResourceManager.GetString("FilterAttributeTypeVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeginsWith.
        /// </summary>
        internal static string FilterRelationTypeBeginsWith {
            get {
                return ResourceManager.GetString("FilterRelationTypeBeginsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        internal static string FilterRelationTypeContains {
            get {
                return ResourceManager.GetString("FilterRelationTypeContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndsWith.
        /// </summary>
        internal static string FilterRelationTypeEndsWith {
            get {
                return ResourceManager.GetString("FilterRelationTypeEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excludes.
        /// </summary>
        internal static string FilterRelationTypeExcludes {
            get {
                return ResourceManager.GetString("FilterRelationTypeExcludes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InRange.
        /// </summary>
        internal static string FilterRelationTypeInRange {
            get {
                return ResourceManager.GetString("FilterRelationTypeInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is.
        /// </summary>
        internal static string FilterRelationTypeIs {
            get {
                return ResourceManager.GetString("FilterRelationTypeIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsNot.
        /// </summary>
        internal static string FilterRelationTypeIsNot {
            get {
                return ResourceManager.GetString("FilterRelationTypeIsNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LessThan.
        /// </summary>
        internal static string FilterRelationTypeLessThan {
            get {
                return ResourceManager.GetString("FilterRelationTypeLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MoreThan.
        /// </summary>
        internal static string FilterRelationTypeMoreThan {
            get {
                return ResourceManager.GetString("FilterRelationTypeMoreThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string FilterRelationTypeNone {
            get {
                return ResourceManager.GetString("FilterRelationTypeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon video {
            get {
                object obj = ResourceManager.GetObject("video", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
