//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dvbseserviceview.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ServiceFileDVBS {
            get {
                return ((string)(this["ServiceFileDVBS"]));
            }
            set {
                this["ServiceFileDVBS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ServiceFileDVBC {
            get {
                return ((string)(this["ServiceFileDVBC"]));
            }
            set {
                this["ServiceFileDVBC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ServiceFileDVBT {
            get {
                return ((string)(this["ServiceFileDVBT"]));
            }
            set {
                this["ServiceFileDVBT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DVBSColumnHeaderWidth {
            get {
                return ((string)(this["DVBSColumnHeaderWidth"]));
            }
            set {
                this["DVBSColumnHeaderWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DVBTColumnHeaderWidth {
            get {
                return ((string)(this["DVBTColumnHeaderWidth"]));
            }
            set {
                this["DVBTColumnHeaderWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DVBCColumnHeaderWidth {
            get {
                return ((string)(this["DVBCColumnHeaderWidth"]));
            }
            set {
                this["DVBCColumnHeaderWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilterColumnHeaderWidth {
            get {
                return ((string)(this["FilterColumnHeaderWidth"]));
            }
            set {
                this["FilterColumnHeaderWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FilterOptionExclude {
            get {
                return ((bool)(this["FilterOptionExclude"]));
            }
            set {
                this["FilterOptionExclude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EITFile {
            get {
                return ((string)(this["EITFile"]));
            }
            set {
                this["EITFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EITColumnHeaderWidth {
            get {
                return ((string)(this["EITColumnHeaderWidth"]));
            }
            set {
                this["EITColumnHeaderWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string servicedifferentialfile1 {
            get {
                return ((string)(this["servicedifferentialfile1"]));
            }
            set {
                this["servicedifferentialfile1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string servicedifferentialfile2 {
            get {
                return ((string)(this["servicedifferentialfile2"]));
            }
            set {
                this["servicedifferentialfile2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string servicedifferentialnetworktype {
            get {
                return ((string)(this["servicedifferentialnetworktype"]));
            }
            set {
                this["servicedifferentialnetworktype"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cmpName {
            get {
                return ((bool)(this["cmpName"]));
            }
            set {
                this["cmpName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cmpProvider {
            get {
                return ((bool)(this["cmpProvider"]));
            }
            set {
                this["cmpProvider"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cmpNetwork {
            get {
                return ((bool)(this["cmpNetwork"]));
            }
            set {
                this["cmpNetwork"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cmpOnid {
            get {
                return ((bool)(this["cmpOnid"]));
            }
            set {
                this["cmpOnid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cmpVideo {
            get {
                return ((bool)(this["cmpVideo"]));
            }
            set {
                this["cmpVideo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cmpAudio {
            get {
                return ((bool)(this["cmpAudio"]));
            }
            set {
                this["cmpAudio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cmpPmt {
            get {
                return ((bool)(this["cmpPmt"]));
            }
            set {
                this["cmpPmt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cmpPcr {
            get {
                return ((bool)(this["cmpPcr"]));
            }
            set {
                this["cmpPcr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cmpType {
            get {
                return ((bool)(this["cmpType"]));
            }
            set {
                this["cmpType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cmpFreeCaMode {
            get {
                return ((bool)(this["cmpFreeCaMode"]));
            }
            set {
                this["cmpFreeCaMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cmpCaSystemId {
            get {
                return ((bool)(this["cmpCaSystemId"]));
            }
            set {
                this["cmpCaSystemId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cmpLcn {
            get {
                return ((bool)(this["cmpLcn"]));
            }
            set {
                this["cmpLcn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cmpBouquet {
            get {
                return ((bool)(this["cmpBouquet"]));
            }
            set {
                this["cmpBouquet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cmpFeatures {
            get {
                return ((bool)(this["cmpFeatures"]));
            }
            set {
                this["cmpFeatures"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cmpOnlyCompareCommonMux {
            get {
                return ((bool)(this["cmpOnlyCompareCommonMux"]));
            }
            set {
                this["cmpOnlyCompareCommonMux"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columnNumber {
            get {
                return ((bool)(this["columnNumber"]));
            }
            set {
                this["columnNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columnName {
            get {
                return ((bool)(this["columnName"]));
            }
            set {
                this["columnName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columnProvider {
            get {
                return ((bool)(this["columnProvider"]));
            }
            set {
                this["columnProvider"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columnFrequency {
            get {
                return ((bool)(this["columnFrequency"]));
            }
            set {
                this["columnFrequency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columnPosition {
            get {
                return ((bool)(this["columnPosition"]));
            }
            set {
                this["columnPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columnNetwork {
            get {
                return ((bool)(this["columnNetwork"]));
            }
            set {
                this["columnNetwork"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columnSid {
            get {
                return ((bool)(this["columnSid"]));
            }
            set {
                this["columnSid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columnTsid {
            get {
                return ((bool)(this["columnTsid"]));
            }
            set {
                this["columnTsid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columnNid {
            get {
                return ((bool)(this["columnNid"]));
            }
            set {
                this["columnNid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columnOnid {
            get {
                return ((bool)(this["columnOnid"]));
            }
            set {
                this["columnOnid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columnVideo {
            get {
                return ((bool)(this["columnVideo"]));
            }
            set {
                this["columnVideo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columnAudio {
            get {
                return ((bool)(this["columnAudio"]));
            }
            set {
                this["columnAudio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columnPmt {
            get {
                return ((bool)(this["columnPmt"]));
            }
            set {
                this["columnPmt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columnPcr {
            get {
                return ((bool)(this["columnPcr"]));
            }
            set {
                this["columnPcr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columnType {
            get {
                return ((bool)(this["columnType"]));
            }
            set {
                this["columnType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columnFreeCaMode {
            get {
                return ((bool)(this["columnFreeCaMode"]));
            }
            set {
                this["columnFreeCaMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columnCaSystemId {
            get {
                return ((bool)(this["columnCaSystemId"]));
            }
            set {
                this["columnCaSystemId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columnLcn {
            get {
                return ((bool)(this["columnLcn"]));
            }
            set {
                this["columnLcn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columnBouquet {
            get {
                return ((bool)(this["columnBouquet"]));
            }
            set {
                this["columnBouquet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columnFeatures {
            get {
                return ((bool)(this["columnFeatures"]));
            }
            set {
                this["columnFeatures"] = value;
            }
        }
    }
}
